name: Umami CI/CD

on:
  push:
    branches: [master]

env:
  DATABASE_TYPE: postgresql
  SKIP_DB_CHECK: 1
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKER_REPOSITORY: reasatrafio29/edistys-analytics
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn test
      - run: yarn build

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: reasatrafio29/edistys-analytics
          tags: |
            ${{ github.ref_name }}
            latest
          push: true
          secrets: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
