# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Node.js CI

# on: [push]

# env:
#   DATABASE_TYPE: postgresql
#   SKIP_DB_CHECK: 1

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         include:
#         - node-version: 18.17
#           db-type: postgresql
#         - node-version: 18.17
#           db-type: mysql

#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v4
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'yarn'
#       env:
#         DATABASE_TYPE: ${{ matrix.db-type }}
#     - run: npm install --global yarn
#     - run: yarn install
#     - run: yarn test
#     - run: yarn build

name: Build Docker images and Deploy

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/edistys-analytics:${{ github.ref_name == 'main' && 'latest'  }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DATABASE_URI=${{ secrets.DATABASE_URI }}

      - name: Trigger Dokploy Deployment
        if: success() # Only run if the Docker build succeeds
        run: |
          response=$(curl -X 'POST' \
            "${{ secrets.DOKPLOY_URL }}/api/application.deploy" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer ${{ secrets.DOKPLOY_AUTH_TOKEN }}" \
            -d "{\"applicationId\": \"${{ secrets.DOKPLOY_APPLICATION_ID }}\"}" \
            -w "%{http_code}" \
            -o /dev/null \
            -s)

          if [ "$response" -ne 200 ]; then
            echo "Deployment failed with status code: $response"
            exit 1
          fi
        env:
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
          DOKPLOY_AUTH_TOKEN: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          DOKPLOY_APPLICATION_ID: ${{ secrets.DOKPLOY_APPLICATION_ID }}